//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FiveDataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Institution
    {
        public int InstitutionId { get; set; }
        public Nullable<int> InstitutionCode { get; set; }
        public string InstitutionName { get; set; }
        public Nullable<short> InstitutionStar { get; set; }
        public Nullable<System.DateTimeOffset> CreatedAt { get; set; }
        public Nullable<System.DateTimeOffset> LastModifiedAt { get; set; }
    }
}
