//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FiveDataLayer.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockType
    {
        public int StockTypeId { get; set; }
        public string StockTypeName { get; set; }
        public string description { get; set; }
        public Nullable<System.DateTimeOffset> CreatedAt { get; set; }
    }
}
